INSERT INTO app(link, name, image, about, category) VALUES ('/terminal', 'Terminal', 'img/app_covers/terminal.jpg', 'App by Wave', '2018_2');
INSERT INTO app(link, name, image, about, category) VALUES ('/snake', 'Snake', 'img/app_covers/snake.jpg', 'Game by Wave', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/yetanothergame', 'https://yet-another-game.ml/', 'Yet Another Game', 'img/app_covers/yetanothergame.jpg', 'Game by Yet Another Game', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/simplegame', 'https://simplegame.ru.com/', 'Simple Game', 'img/app_covers/simplegame.jpg', 'Game by Simple Name', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/tron', 'https://codeloft.ru', 'Tron: Remastered', 'img/app_covers/tron.jpg', 'Game by codeloft', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/ketnipz', 'https://playketnipz.ru/', 'Ketnipz', 'img/app_covers/ketnipz.jpg', 'Game by DeadMolesStudio', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/rpsarena', 'http://rpsarena.ru', 'RPS Arena', 'img/app_covers/rps.jpg', 'Game by 42', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/blep', 'https://blep.me', 'Blep', 'img/app_covers/blep.jpg', 'Game by Stacktivity', '2018_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/catchthealien', 'https://itberries-frontend.herokuapp.com/', 'Catch the alien!', 'img/app_covers/catch.jpg', 'Game by Itberries', '2018_1');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/guardians', 'https://chunk-frontend.herokuapp.com/', 'Guardians', 'img/app_covers/guardians.jpg', 'Game by Chunk', '2017_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/rhytmblast', 'https://glitchless.surge.sh/', 'Rhytm Blast', 'img/app_covers/rhytmblast.jpg', 'Game by Glitchless', '2017_2');
INSERT INTO app(link, url, name, image, about, category) VALUES ('/proto', 'https://rasseki.pro/', '__proto__', 'img/app_covers/proto.jpg', 'Game by __proto__', '2018_2');